name: "Release"

on:
  release:
    types:
      - "published"

permissions: {}

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: "Checkout the repository"
        uses: "actions/checkout@v4"

      - name: "Adjust version number"
        shell: "bash"
        run: |
          TAG="${{ github.event.release.tag_name }}"
          TAG="${TAG#v}"
          yq -i -o json ".version=\"$TAG\"" \
            "${{ github.workspace }}/custom_components/silam_pollen/manifest.json"

      - name: "ZIP the integration directory"
        shell: "bash"
        run: |
          cd "${{ github.workspace }}/custom_components/silam_pollen"
          zip silam_pollen.zip -r ./

      - name: "Upload the ZIP file to the release"
        uses: softprops/action-gh-release@v2.2.1
        with:
          files: ${{ github.workspace }}/custom_components/silam_pollen/silam_pollen.zip
